version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.19
    working_directory: ~/project

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Angular CLI globally
          command: npm install -g @angular/cli
      - run:
          name: Install dependencies
          command: npm install

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build Angular app
          command: ng build --configuration=production

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: ng test --watch=false --browsers=ChromeHeadless

workflows:
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
