apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello
spec:
  replicas: 1
  selector:
    matchLabels: {app: spring-hello}
  template:
    metadata:
      labels: {app: spring-hello}
    spec:
      containers:
      - name: spring-hello
        image: qurupeco/spring-hello
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-hello-nodeport
spec:
  type: NodePort
  selector:
    app: spring-hello
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
